### PR TITLE
Added epoll support on Systems that support that

### PR DESCRIPTION
**Pull request by jimmykane**
Added epoll support on Systems that support that. I hope it is ok for windows systems that may not have that!

### CODE REVIEW

**Comment by jimmykane** [comment]
Closing that to update to latest!

**Comment by Aaryans** [comment]
Still getting the same error :( . I am on windows XP using cygwin .

**Comment by janrueth** [comment]
This is no error, it is just an advanced method that windows does not support, therefore it informs you about that and uses the second best method

**Comment by cytec** [comment]
shouldn't this be logged in debug mode only?

just asking because for most users it shouldn't be that interesting to know...

**Comment by janrueth** [comment]
Hm maybe, at this time the logging interface is just not setup...

**Comment by jimmykane** [comment]
Maybe not give warning and just say using select, or using epoll for just info.

**Comment by janrueth** [comment]
http://git.io/6wyTSg This commit fixes it

**Pull request merged**
