### PR TITLE
Plugins have to keep requesting priority

### PR DESCRIPTION
**Pull request by theospears**
Previously once a plugin requested priority it would always have it,
now it must be explicitly requested again during every request

### CODE REVIEW

**Comment by janrueth** [comment]
But that is the desired behavior, only to have priority once abd having to request it again

**Comment by theospears** [comment]
I think my description of the patch was unclear. The current behaviour of the code is that plugins can continue to have priority, even if they don't keep requesting it. This patch changes the behaviour so they have to keep requesting it.

**Comment by janrueth** [comment]
Oh :) I'll take a look at it

**Comment by janrueth** [comment]
I will add this change manually, as I would need to merge it manually, as automerge is not possible :) just one line of code :) so I'll close here and will push a fix in a sec

**Pull request closed without merging**
